openapi: 3.0.0
info:
  title: Kooltra Accounts API
  description: Account API for REST operation within counterparty data
  version: 0.1.0
servers:
  - url: https://sandbox.api.kooltra.com/v1/accounts
paths:
  '/':
    get:
      responses:
        '200':
          description: OK
          content:
            "application/json":
              schema: 
                type: array
                items:
                  "$ref": "#/components/schemas/Account"
            

components:
  schemas:
    Account:
      type: object
      properties:
        code:
          type: string